services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "10033:10033"
    volumes:
      - ./instances:/instances
      - ./miu-client:/miu-client
      - ./app:/app # for hot-reloading
